import schedule 
import psutil
import time 
import sys
import os
import smtplib
from email.message import EmailMessage

def ProcessInfo(Directoryname,receiverEmail):

    ret =os.path.exists(Directoryname)
    if(ret == True ):
        ret=os.path.isdir(Directoryname)
        if(ret == False):
            print("No such Directory found ")


            

    else:
        os.mkdir(Directoryname)
        
    


    timestamp =time.strftime("%d-%m-%Y_%H-%M-%S")
    Filename = os.path.join(Directoryname,f"Process_Log_File_{timestamp}.log")
    fobj=open(Filename,"a")
    
    
    fobj.write("-"*100+"\n")
    fobj.write(f"Process Log File \n Created at time :{time.ctime()}\n")
    fobj.write("-"*100+"\n")

    for proc in psutil.process_iter():
        info = proc.as_dict(attrs=["pid","name","username"])
        fobj.write("-"*100+"\n")
        
        fobj.write("\n")
        fobj.write(f"Process Id : {info.get("pid")}\n")
        fobj.write(f"Process Name : {info.get("name")}\n")
        fobj.write(f"Username: {info.get("username")}\n")
        
        fobj.write("-"*100+"\n")

    fobj.write("-"*100+"\n")
    fobj.write("-"*100+"\n")
    fobj.write("End of Log File\n")
    fobj.write("-"*100+"\n")
    fobj.write("-"*100+"\n")

    print("Log File Created Sucsessfully")
    fobj.close()

    message = EmailMessage()
    message["From"]="y31503036@gmail.com"
    message["To"]=receiverEmail
    message["Subject"] = f"Process Survilence Log_{timestamp}"

    body ="Dear Recipient,\nPlease find attached the latest **Process Surveillance Report**, automatically generated by the Process Surveillance System.\nThis report contains the execution logs and monitoring results from the most recent surveillance cycle. It has been generated to provide visibility into process execution, facilitate operational monitoring, and support timely identification of any exceptions or anomalies.\nShould any warnings, errors, or irregularities be identified within the attached log, please review them in accordance with your organization's established operational procedures.\n\n\n**This is a system-generated email. Please do not reply to this message.**\nThank you for your attention.\n\nKind regards,\n**Process Surveillance System**\n*Automated Monitoring & Reporting Service*"
    message.set_content(body)
    
    fobjmail=open(Filename,"rb")
    f_data =fobjmail.read()
    f_name =fobjmail.name
    
    message.add_attachment(f_data,maintype="text",subtype="plain",filename = f_name)
    
    smtp=smtplib.SMTP_SSL("smtp.gmail.com",465)
    smtp.login("y31503036@gmail.com","gdgy mcuq ipup xanw")
    smtp.send_message(message)

    print("Mail Succesfully Sent!...")
    
    smtp.quit()




def main():
    if(len(sys.argv)==3):
        schedule.every(10).seconds.do(ProcessInfo,sys.argv[1],sys.argv[2])

        while(1):

            schedule.run_pending()
            time.sleep(1)

    else:
        print("Invalid no.of Arguments \n Enter thecorrect no.of arguments")



if __name__ =="__main__":
    main()